#ifndef WATER_SETTINGS_INCLUDED
#define WATER_SETTINGS_INCLUDED

#define ZERO_EPS 0.0001
#define WATERFALL_HUMP 0.3
#define WATER_VERTICAL_THRESHOLD 0.01
#define WATER_CEILING_SEPARATION 0.0025
#define WATER_VERTICAL_OFFSET 0.0001
#define FLOW_LIMIT_OFFSET 0.001
#define FLOW_LIMIT_THRESHOLD 0.01
#define MAX_SPILLING_OFFSET_NON_EDGE -0.54
#define MAX_SPILLING_OFFSET_EDGE -0.9
#define SPILLING_OFFSET_VARIATION 0.2
#define SPILLING_OFFSET_EXPONENT 0.25
#define MAX_EDGE_OFFSET 0.15
#define EDGE_OFFSET_MAX_OUTFLOW 0.01
#define EDGE_OFFSET_MAX_DEPTH 0.1
#define EDGE_OFFSET_MIN_DEPTH 0.05
#define EDGE_OFFSET_DEPTH_SPAN EDGE_OFFSET_MIN_DEPTH - EDGE_OFFSET_MAX_DEPTH
#define MAP_BORDER_TOLERANCE 0.15
#define INITIAL_MAX -999999
#define INITIAL_MIN 999999

#endif // WATER_SETTINGS_INCLUDED
