using System;
using System.Collections.Generic;

namespace TimberCommons.Tests;

static class Program {
  static readonly List<(string Name, Action Test)> Tests = [
      ("GrowthRateModifier combines strongest boost and moderator", GrowthRateModifierTests.CombinesModifiers),
      ("GrowthRateModifier recalculates after unregister", GrowthRateModifierTests.RecalculatesAfterUnregister),
      ("GrowthRateModifier ignores inactive growables", GrowthRateModifierTests.IgnoresInactiveGrowables),
      ("GoodConsumingIrrigationTower scales consumption from coverage",
          GoodConsumingIrrigationTowerTests.ScalesConsumptionFromCoverage),
      ("GoodConsumingIrrigationTower toggles consumption from coverage",
          GoodConsumingIrrigationTowerTests.TogglesConsumptionFromCoverage),
      ("GoodConsumingIrrigationTower moisturizes only when consumption can run",
          GoodConsumingIrrigationTowerTests.MoisturizesOnlyWhenConsumptionCanRun),
      ("GoodConsumingIrrigationTower multiplies finished-building efficiency providers",
          GoodConsumingIrrigationTowerTests.MultipliesFinishedBuildingEfficiencyProviders),
      ("ManufactoryIrrigationTower scales recipe duration from coverage",
          ManufactoryIrrigationTowerTests.ScalesRecipeDurationFromCoverage),
      ("ManufactoryIrrigationTower reports no tiles instead of supply time at zero coverage",
          ManufactoryIrrigationTowerTests.ReportsNoTilesAtZeroCoverage),
      ("ManufactoryIrrigationTower moisturizes only when unblocked and ready",
          ManufactoryIrrigationTowerTests.MoisturizesOnlyWhenUnblockedAndReady),
      ("ManufactoryIrrigationTower reports production efficiency only when ready",
          ManufactoryIrrigationTowerTests.ReportsProductionEfficiencyOnlyWhenReady),
      ("IrrigationTower initializes flat-foundation coverage from lifecycle",
          IrrigationTowerTests.InitializesFlatFoundationCoverageFromLifecycle),
      ("IrrigationTower starts moisture override once and removes it on exit",
          IrrigationTowerTests.StartsMoistureOverrideOnceAndRemovesItOnExit),
      ("IrrigationTower starts moisture override with distance-based desert levels",
          IrrigationTowerTests.StartsMoistureOverrideWithDistanceBasedDesertLevels),
      ("IrrigationTower unsubscribes from runtime events on exit",
          IrrigationTowerTests.UnsubscribesFromRuntimeEventsOnExit),
      ("IrrigationTower removes moisture override when blocked",
          IrrigationTowerTests.RemovesMoistureOverrideWhenBlocked),
      ("IrrigationTower recalculates coverage when efficiency changes",
          IrrigationTowerTests.RecalculatesCoverageWhenEfficiencyChanges),
      ("IrrigationTower saves and claims active moisture override",
          IrrigationTowerTests.SavesAndClaimsActiveMoistureOverride),
      ("IrrigationTower restores saved efficiency",
          IrrigationTowerTests.RestoresSavedEfficiency),
      ("IrrigationTower recalculates coverage when terrain eligibility changes",
          IrrigationTowerTests.RecalculatesCoverageWhenTerrainEligibilityChanges),
      ("IrrigationTower refreshes moisture override when coverage changes",
          IrrigationTowerTests.RefreshesMoistureOverrideWhenCoverageChanges),
      ("IrrigationTower recalculates coverage when soil barrier is built",
          IrrigationTowerTests.RecalculatesCoverageWhenSoilBarrierIsBuilt),
      ("IrrigationTower recalculates coverage when soil barrier is deleted",
          IrrigationTowerTests.RecalculatesCoverageWhenSoilBarrierIsDeleted),
      ("IrrigationTower returns preview range for unfinished building",
          IrrigationTowerTests.ReturnsPreviewRangeForUnfinishedBuilding),
      ("IrrigationTower returns reachable or eligible range for finished building",
          IrrigationTowerTests.ReturnsReachableOrEligibleRangeForFinishedBuilding),
      ("IrrigationTower post-placement change recalculates preview positioning",
          IrrigationTowerTests.PostPlacementChangeRecalculatesPreviewPositioning),
      ("IrrigationTower post-initialize recalculates preview positioning",
          IrrigationTowerTests.PostInitializeEntityRecalculatesPreviewPositioning),
      ("IrrigationTower delays mechanical efficiency changes",
          IrrigationTowerTests.DelaysMechanicalEfficiencyChanges),
      ("IrrigationTower refreshes range highlight only while selected",
          IrrigationTowerTests.RefreshesRangeHighlightOnlyWhileSelected),
      ("IrrigationTower ignores irrelevant terrain events",
          IrrigationTowerTests.IgnoresIrrelevantTerrainEvents),
      ("IrrigationTower ignores irrelevant soil barrier build events",
          IrrigationTowerTests.IgnoresIrrelevantSoilBarrierBuildEvents),
      ("IrrigationTower ignores irrelevant soil barrier delete events",
          IrrigationTowerTests.IgnoresIrrelevantSoilBarrierDeleteEvents),
      ("IrrigationTower calculates coverage from two-by-two foundation boundary",
          IrrigationTowerTests.CalculatesCoverageFromTwoByTwoFoundationBoundary),
      ("IrrigationTower uses all foundation tiles when ground-only is disabled",
          IrrigationTowerTests.UsesAllFoundationTilesWhenGroundOnlyIsDisabled),
      ("IrrigationTower clips coverage at map bounds",
          IrrigationTowerTests.ClipsCoverageAtMapBounds),
      ("IrrigationTower terrain obstacles cut off disconnected tiles",
          IrrigationTowerTests.TerrainObstaclesCutOffDisconnectedTiles),
      ("IrrigationTower soil barriers cut off disconnected tiles",
          IrrigationTowerTests.SoilBarriersCutOffDisconnectedTiles),
      ("BlockContaminationRangeEffect applies and replaces contamination override",
          BlockContaminationRangeEffectTests.AppliesAndReplacesContaminationOverride),
      ("BlockContaminationRangeEffect saves and claims loaded override",
          BlockContaminationRangeEffectTests.SavesAndClaimsLoadedOverride),
      ("ModifyGrowableGrowthRangeEffect applies and resets matching growables",
          ModifyGrowableGrowthRangeEffectTests.AppliesAndResetsMatchingGrowables),
      ("ModifyGrowableGrowthRangeEffect honors template and component filters",
          ModifyGrowableGrowthRangeEffectTests.HonorsTemplateAndComponentFilters),
      ("ModifyGrowableGrowthRangeEffect handles new initialized entities",
          ModifyGrowableGrowthRangeEffectTests.HandlesNewInitializedEntities),
  ];

  static int Main() {
    return TestRunner.Run(Tests);
  }
}
