using System;
using System.Collections.Generic;

namespace Automation.Tests;

static class Program {
  static readonly List<(string Name, Action Test)> Tests = [
      // AutomationSystem
      ("AutomationBehavior creates dynamic component only once", AutomationBehaviorTests.GetOrCreateCachesComponent),
      ("AutomationBehavior reports missing dynamic component", AutomationBehaviorTests.GetOrThrowReportsMissingComponent),
      ("AutomationBehavior creates component with Awake callback", AutomationBehaviorTests.GetOrCreateCallsAwake),
      ("AutomationBehavior replays finished callback after late creation", AutomationBehaviorTests.GetOrCreateAfterFinished),
      ("AutomationBehavior replays initialized callback after late creation", AutomationBehaviorTests.GetOrCreateAfterInitialized),
      ("AutomationBehavior replays finished and initialized callbacks in order",
          AutomationBehaviorTests.GetOrCreateAfterFinishedAndInitialized),
      ("AutomationBehavior forwards lifecycle callbacks to existing dynamic components",
          AutomationBehaviorTests.ForwardsLifecycleCallbacks),
      ("AutomationBehavior delete forwards to dynamic components", AutomationBehaviorTests.DeleteEntityForwardsToComponents),
      ("GameAutomationConflictDetector detects FillValve state changing rules",
          GameAutomationConflictDetectorTests.DetectsFillValveStateChangingRules),
      ("GameAutomationConflictDetector detects ThrottlingValve state changing rules",
          GameAutomationConflictDetectorTests.DetectsThrottlingValveStateChangingRules),
      ("GameAutomationConflictDetector detects state changing rules for other buildings",
          GameAutomationConflictDetectorTests.DetectsStateChangingRulesForOtherBuildings),
      ("GameAutomationConflictDetector ignores signal rules", GameAutomationConflictDetectorTests.IgnoresSignalRules),
      ("GameAutomationConflictDetector ignores notification rules",
          GameAutomationConflictDetectorTests.IgnoresNotificationRules),
      ("GameAutomationConflictDetector ignores disabled rules", GameAutomationConflictDetectorTests.IgnoresDisabledRules),
      ("GameAutomationConflictDetector detects state changing action names",
          GameAutomationConflictDetectorTests.DetectsStateChangingActionNames),
      ("GameAutomationConflictDetector ignores non-state-changing action names",
          GameAutomationConflictDetectorTests.IgnoresNonStateChangingActionNames),
      ("GameAutomationRuleSaveConflictDetector finds rule save conflicts by rule number",
          GameAutomationConflictDetectorTests.FindsRuleSaveConflictsByRuleNumber),
      ("GameAutomationRuleSaveConflictDetector ignores conflicts when game automation is disabled",
          GameAutomationConflictDetectorTests.IgnoresRuleSaveConflictsWhenGameAutomationIsDisabled),
      ("GameAutomationRuleSaveConflictDetector ignores disabled and deleted rule save conflicts",
          GameAutomationConflictDetectorTests.IgnoresDisabledAndDeletedRuleSaveConflicts),

      // ScriptingEngine.Parser
      ("Python parser preserves math and logical precedence", ParserTests.PythonParserPreservesPrecedence),
      ("Python parser handles strings and concat", ParserTests.PythonParserHandlesStringsAndConcat),
      ("Python parser parses signal comparisons and actions", ParserTests.PythonParserParsesSignalsAndActions),
      ("Lisp parser round-trips comparison and math expressions", ParserTests.LispParserRoundTripsExpressions),
      ("Parsers can round-trip between Python and Lisp", ParserTests.ParsersRoundTripAcrossSyntaxes),
      ("Python parser rejects malformed expressions", ParserTests.PythonParserRejectsMalformedExpressions),
      ("Lisp parser rejects malformed expressions", ParserTests.LispParserRejectsMalformedExpressions),
      ("ParserFactory selects parser by explicit prefix", ParserFactoryTests.SelectsParserByExplicitPrefix),
      ("ParserFactory uses preferred parser when no prefix is present", ParserFactoryTests.UsesPreferredParser),
      ("ParserFactory parses valid conditions and actions", ParserFactoryTests.ParsesValidConditionsAndActions),
      ("ParserFactory rejects invalid conditions", ParserFactoryTests.RejectsInvalidConditions),
      ("ParserFactory rejects non-action expressions", ParserFactoryTests.RejectsNonActionExpressions),

      // ScriptingEngine.Expressions
      ("ScriptValue stores fixed precision numbers", ExpressionTests.ScriptValueStoresFixedPrecisionNumbers),
      ("ScriptValue arithmetic uses raw fixed precision", ExpressionTests.ScriptValueArithmeticUsesRawFixedPrecision),
      ("ScriptValue rejects invalid value access", ExpressionTests.ScriptValueRejectsInvalidAccess),
      ("MathOperator executes numeric functions", ExpressionTests.MathOperatorExecutesNumericFunctions),
      ("ComparisonOperator executes number and string comparisons", ExpressionTests.ComparisonOperatorExecutesComparisons),
      ("LogicalOperator executes boolean composition", ExpressionTests.LogicalOperatorExecutesBooleanComposition),
      ("ConcatOperator concatenates number and string values", ExpressionTests.ConcatOperatorConcatenatesValues),
      ("Operators reject invalid operands", ExpressionTests.OperatorsRejectInvalidOperands),

      // ScriptingEngine.Core
      ("ScriptingService registers and looks up scriptables", ScriptingServiceTests.RegistersAndLooksUpScriptables),
      ("ScriptingService reports unknown scriptables", ScriptingServiceTests.UnknownScriptableReportsParsingError),
      ("ScriptingService registers and unregisters signals",
          ScriptingServiceTests.RegistersAndUnregistersSignalsFromExpression),
      ("ScriptingService installs and uninstalls actions", ScriptingServiceTests.InstallsAndUninstallsActionsFromExpression),
      ("ScriptingService maintains execution stack", ScriptingServiceTests.MaintainsExecutionStack),
      ("ScriptingService wraps signal callbacks with execution stack",
          ScriptingServiceTests.NotifySignalListenerWrapsCallbackWithExecutionStack),

      // ScriptingEngine.ScriptableComponents
      ("ValueDef range check accepts values in range", ValueDefTests.RangeCheckValidatorAcceptsValuesInRange),
      ("ValueDef range check rejects values outside range", ValueDefTests.RangeCheckValidatorRejectsValuesOutsideRange),
      ("ValueDef range check supports single boundary", ValueDefTests.RangeCheckValidatorSupportsSingleBoundary),

      // ScriptingEngine.ScriptableComponents.Components
      ("AbstractStatusTracker tracks actions and reports duplicates",
          AbstractStatusTrackerTests.TracksActionsAndReportsDuplicates),
      ("AbstractStatusTracker tracks signals and reports duplicates",
          AbstractStatusTrackerTests.TracksSignalsAndReportsDuplicates),
      ("AbstractStatusTracker notifies listeners only when value changes",
          AbstractStatusTrackerTests.NotifiesListenersOnlyWhenValueChanges),
      ("AbstractStatusTracker notifies same listener once for multiple signal registrations",
          AbstractStatusTrackerTests.NotifiesSameListenerOnceForMultipleSignalRegistrations),
      ("AutomatorScriptableComponent exposes signal for transmitter automator",
          AutomatorScriptableComponentTests.ExposesSignalForTransmitterAutomator),
      ("AutomatorScriptableComponent hides signal for missing or non-transmitter automator",
          AutomatorScriptableComponentTests.HidesSignalForMissingOrNonTransmitterAutomator),
      ("AutomatorScriptableComponent reads automator state", AutomatorScriptableComponentTests.ReadsAutomatorState),
      ("AutomatorScriptableComponent builds state signal definition",
          AutomatorScriptableComponentTests.BuildsStateSignalDefinition),
      ("AutomatorScriptableComponent reports unknown signal", AutomatorScriptableComponentTests.ReportsUnknownSignal),
      ("ConstructableScriptableComponent exposes signals for unfinished building",
          ConstructableScriptableComponentTests.ExposesSignalsForUnfinishedBuilding),
      ("ConstructableScriptableComponent hides signals for finished building",
          ConstructableScriptableComponentTests.HidesSignalsForFinishedBuilding),
      ("ConstructableScriptableComponent reads state and progress signals",
          ConstructableScriptableComponentTests.ReadsStateAndProgressSignals),
      ("ConstructableScriptableComponent builds signal definitions",
          ConstructableScriptableComponentTests.BuildsSignalDefinitions),
      ("ConstructableScriptableComponent reports unknown signal",
          ConstructableScriptableComponentTests.ReportsUnknownSignal),
      ("CollectableScriptableComponent exposes signal for collecting building",
          CollectableScriptableComponentTests.ExposesSignalForCollectingBuilding),
      ("CollectableScriptableComponent hides signal for missing collecting components",
          CollectableScriptableComponentTests.HidesSignalForMissingCollectingComponents),
      ("CollectableScriptableComponent builds ready signal definition",
          CollectableScriptableComponentTests.BuildsReadySignalDefinition),
      ("CollectableScriptableComponent tracks ready yielders and notifies listeners",
          CollectableScriptableComponentTests.TracksReadyYieldersAndNotifiesListeners),
      ("CollectableScriptableComponent ignores yielders outside lumberjack cutting area",
          CollectableScriptableComponentTests.IgnoresYieldersOutsideLumberjackCuttingArea),
      ("CollectableScriptableComponent reports unknown signal",
          CollectableScriptableComponentTests.ReportsUnknownSignal),
      ("DebugScriptableComponent exposes definitions", DebugScriptableComponentTests.ExposesDefinitions),
      ("DebugScriptableComponent executes log actions", DebugScriptableComponentTests.ExecutesLogActions),
      ("DebugScriptableComponent registers ticker callbacks", DebugScriptableComponentTests.RegistersTickerCallbacks),
      ("DistrictScriptableComponent exposes signals for district building",
          DistrictScriptableComponentTests.ExposesSignalsForDistrictBuilding),
      ("DistrictScriptableComponent exposes resource signals sorted by good display name",
          DistrictScriptableComponentTests.ExposesResourceSignalsSortedByGoodDisplayName),
      ("DistrictScriptableComponent hides signals for missing district building",
          DistrictScriptableComponentTests.HidesSignalsForMissingDistrictBuilding),
      ("DistrictScriptableComponent reads population beds and resource signals",
          DistrictScriptableComponentTests.ReadsPopulationBedsAndResourceSignals),
      ("DistrictScriptableComponent builds signal definitions",
          DistrictScriptableComponentTests.BuildsSignalDefinitions),
      ("DistrictScriptableComponent tick updates tracked resources and notifies listeners",
          DistrictScriptableComponentTests.TickUpdatesTrackedResourcesAndNotifiesListeners),
      ("DistrictScriptableComponent tick resets tracked resources when district disconnects",
          DistrictScriptableComponentTests.TickResetsTrackedResourcesWhenDistrictDisconnects),
      ("DistrictScriptableComponent population events notify matching listeners",
          DistrictScriptableComponentTests.PopulationEventsNotifyMatchingListeners),
      ("DistrictScriptableComponent reports unknown signal", DistrictScriptableComponentTests.ReportsUnknownSignal),
      ("DynamiteScriptableComponent exposes actions for dynamite",
          DynamiteScriptableComponentTests.ExposesActionsForDynamite),
      ("DynamiteScriptableComponent hides actions for missing dynamite",
          DynamiteScriptableComponentTests.HidesActionsForMissingDynamite),
      ("DynamiteScriptableComponent builds action definitions",
          DynamiteScriptableComponentTests.BuildsActionDefinitions),
      ("DynamiteScriptableComponent validates repeat count",
          DynamiteScriptableComponentTests.ValidatesRepeatCount),
      ("DynamiteScriptableComponent executes detonate action by queueing coroutine",
          DynamiteScriptableComponentTests.ExecutesDetonateActionByQueueingCoroutine),
      ("DynamiteScriptableComponent wait and place repeats dynamite in order",
          DynamiteScriptableComponentTests.WaitAndPlaceRepeatsDynamiteInOrder),
      ("DynamiteScriptableComponent installs and uninstalls actions",
          DynamiteScriptableComponentTests.InstallsAndUninstallsActions),
      ("DynamiteScriptableComponent reports unknown action", DynamiteScriptableComponentTests.ReportsUnknownAction),
      ("FlowControlScriptableComponent exposes actions for water source regulator",
          FlowControlScriptableComponentTests.ExposesActionsForWaterSourceRegulator),
      ("FlowControlScriptableComponent hides actions for missing regulator",
          FlowControlScriptableComponentTests.HidesActionsForMissingRegulator),
      ("FlowControlScriptableComponent executes open and close actions",
          FlowControlScriptableComponentTests.ExecutesOpenAndCloseActions),
      ("FlowControlScriptableComponent reports unknown action", FlowControlScriptableComponentTests.ReportsUnknownAction),
      ("FillValveScriptableComponent exposes actions for fill valve",
          FillValveScriptableComponentTests.ExposesActionsForFillValve),
      ("FillValveScriptableComponent hides actions for missing fill valve",
          FillValveScriptableComponentTests.HidesActionsForMissingFillValve),
      ("FillValveScriptableComponent executes open close and set height actions",
          FillValveScriptableComponentTests.ExecutesOpenCloseAndSetHeightActions),
      ("FillValveScriptableComponent builds action definitions for target depth",
          FillValveScriptableComponentTests.BuildsActionDefinitionsForTargetDepth),
      ("FillValveScriptableComponent reports unknown action", FillValveScriptableComponentTests.ReportsUnknownAction),
      ("FloodgateScriptableComponent exposes signal and action for floodgate",
          FloodgateScriptableComponentTests.ExposesSignalAndActionForFloodgate),
      ("FloodgateScriptableComponent hides signal and action for missing floodgate",
          FloodgateScriptableComponentTests.HidesSignalAndActionForMissingFloodgate),
      ("FloodgateScriptableComponent reads and sets floodgate height",
          FloodgateScriptableComponentTests.ReadsAndSetsFloodgateHeight),
      ("FloodgateScriptableComponent does not set same height again",
          FloodgateScriptableComponentTests.DoesNotSetSameHeightAgain),
      ("FloodgateScriptableComponent builds definitions for floodgate height",
          FloodgateScriptableComponentTests.BuildsDefinitionsForFloodgateHeight),
      ("FloodgateScriptableComponent reports unknown signal and action",
          FloodgateScriptableComponentTests.ReportsUnknownSignalAndAction),
      ("InventoryScriptableComponent exposes signals for inventory",
          InventoryScriptableComponentTests.ExposesSignalsForInventory),
      ("InventoryScriptableComponent exposes allowed goods signals for yielder inventory",
          InventoryScriptableComponentTests.ExposesAllowedGoodsSignalsForYielderInventory),
      ("InventoryScriptableComponent hides signals for missing inventory",
          InventoryScriptableComponentTests.HidesSignalsForMissingInventory),
      ("InventoryScriptableComponent reads inventory amounts",
          InventoryScriptableComponentTests.ReadsInventoryAmounts),
      ("InventoryScriptableComponent builds signal definitions",
          InventoryScriptableComponentTests.BuildsSignalDefinitions),
      ("InventoryScriptableComponent exposes emptying actions only for safe output inventory",
          InventoryScriptableComponentTests.ExposesEmptyingActionsOnlyForSafeOutputInventory),
      ("InventoryScriptableComponent executes emptying actions",
          InventoryScriptableComponentTests.ExecutesEmptyingActions),
      ("InventoryScriptableComponent notifies inventory signal listeners",
          InventoryScriptableComponentTests.NotifiesInventorySignalListeners),
      ("InventoryScriptableComponent installs emptying status action",
          InventoryScriptableComponentTests.InstallsEmptyingStatusAction),
      ("InventoryScriptableComponent reports unknown signal and action",
          InventoryScriptableComponentTests.ReportsUnknownSignalAndAction),
      ("LeverScriptableComponent exposes action for lever", LeverScriptableComponentTests.ExposesActionForLever),
      ("LeverScriptableComponent hides action for missing lever", LeverScriptableComponentTests.HidesActionForMissingLever),
      ("LeverScriptableComponent executes set state action", LeverScriptableComponentTests.ExecutesSetStateAction),
      ("LeverScriptableComponent rejects invalid action arguments",
          LeverScriptableComponentTests.RejectsInvalidActionArguments),
      ("LeverScriptableComponent reports unknown action", LeverScriptableComponentTests.ReportsUnknownAction),
      ("ManufactoryScriptableComponent exposes action for manufactory with multiple recipes",
          ManufactoryScriptableComponentTests.ExposesActionForManufactoryWithMultipleRecipes),
      ("ManufactoryScriptableComponent hides action for missing or single recipe manufactory",
          ManufactoryScriptableComponentTests.HidesActionForMissingOrSingleRecipeManufactory),
      ("ManufactoryScriptableComponent builds recipe action definition",
          ManufactoryScriptableComponentTests.BuildsRecipeActionDefinition),
      ("ManufactoryScriptableComponent executes set recipe action",
          ManufactoryScriptableComponentTests.ExecutesSetRecipeAction),
      ("ManufactoryScriptableComponent reports unknown recipe and action",
          ManufactoryScriptableComponentTests.ReportsUnknownRecipeAndAction),
      ("NotificationsScriptableComponent exposes notification actions",
          NotificationsScriptableComponentTests.ExposesNotificationActions),
      ("NotificationsScriptableComponent builds action definitions",
          NotificationsScriptableComponentTests.BuildsActionDefinitions),
      ("NotificationsScriptableComponent executes notice alert and clear actions",
          NotificationsScriptableComponentTests.ExecutesNoticeAlertAndClearActions),
      ("NotificationsScriptableComponent installs and uninstalls actions",
          NotificationsScriptableComponentTests.InstallsAndUninstallsActions),
      ("NotificationsScriptableComponent reports unknown action",
          NotificationsScriptableComponentTests.ReportsUnknownAction),
      ("PausableScriptableComponent exposes actions for pausable building",
          PausableScriptableComponentTests.ExposesActionsForPausableBuilding),
      ("PausableScriptableComponent hides actions for non-pausable building",
          PausableScriptableComponentTests.HidesActionsForNonPausableBuilding),
      ("PausableScriptableComponent executes pause and resume actions",
          PausableScriptableComponentTests.ExecutesPauseAndResumeActions),
      ("PausableScriptableComponent reports unknown action", PausableScriptableComponentTests.ReportsUnknownAction),
      ("PlantableScriptableComponent exposes signal for planting building",
          PlantableScriptableComponentTests.ExposesSignalForPlantingBuilding),
      ("PlantableScriptableComponent hides signal for missing planting components",
          PlantableScriptableComponentTests.HidesSignalForMissingPlantingComponents),
      ("PlantableScriptableComponent builds ready signal definition",
          PlantableScriptableComponentTests.BuildsReadySignalDefinition),
      ("PlantableScriptableComponent updates ready spots through parallel tick and notifies listeners",
          PlantableScriptableComponentTests.UpdatesReadySpotsThroughParallelTickAndNotifiesListeners),
      ("PlantableScriptableComponent updates ready spots immediately when paused",
          PlantableScriptableComponentTests.UpdatesReadySpotsImmediatelyWhenPaused),
      ("PlantableScriptableComponent unregister removes tracker from parallel updates",
          PlantableScriptableComponentTests.UnregisterRemovesTrackerFromParallelUpdates),
      ("PlantableScriptableComponent reports unknown signal",
          PlantableScriptableComponentTests.ReportsUnknownSignal),
      ("PrioritizableScriptableComponent exposes actions for prioritizable building",
          PrioritizableScriptableComponentTests.ExposesActionsForPrioritizableBuilding),
      ("PrioritizableScriptableComponent hides actions for missing component",
          PrioritizableScriptableComponentTests.HidesActionsForMissingPrioritizableComponent),
      ("PrioritizableScriptableComponent executes set and reset haulers actions",
          PrioritizableScriptableComponentTests.ExecutesSetAndResetHaulersActions),
      ("PrioritizableScriptableComponent reports unknown action",
          PrioritizableScriptableComponentTests.ReportsUnknownAction),
      ("SignalsScriptableComponent exposes definitions", SignalsScriptableComponentTests.ExposesDefinitions),
      ("SignalsScriptableComponent sets manual signal values", SignalsScriptableComponentTests.SetsManualSignalValues),
      ("SignalsScriptableComponent validates signal names", SignalsScriptableComponentTests.ValidatesSignalNames),
      ("SignalDispatcher aggregates provider values", SignalDispatcherTests.AggregatesProviderValues),
      ("SignalDispatcher handles manual signal values", SignalDispatcherTests.HandlesManualSignalValues),
      ("SignalDispatcher notifies listeners on signal changes", SignalDispatcherTests.NotifiesListenersOnSignalChanges),
      ("SignalDispatcher rejects duplicate and missing registrations",
          SignalDispatcherTests.RejectsDuplicateAndMissingRegistrations),
      ("SignalDispatcher locks changes while notifying listeners", SignalDispatcherTests.LocksChangesWhileNotifying),
      ("StreamGaugeScriptableComponent exposes signals for stream gauge",
          StreamGaugeScriptableComponentTests.ExposesSignalsForStreamGauge),
      ("StreamGaugeScriptableComponent hides signals for missing stream gauge",
          StreamGaugeScriptableComponentTests.HidesSignalsForMissingStreamGauge),
      ("StreamGaugeScriptableComponent reads stream gauge signals",
          StreamGaugeScriptableComponentTests.ReadsStreamGaugeSignals),
      ("StreamGaugeScriptableComponent builds signal definitions",
          StreamGaugeScriptableComponentTests.BuildsSignalDefinitions),
      ("StreamGaugeScriptableComponent reports unknown signal",
          StreamGaugeScriptableComponentTests.ReportsUnknownSignal),
      ("ThrottlingValveScriptableComponent exposes actions for throttling valve",
          ThrottlingValveScriptableComponentTests.ExposesActionsForThrottlingValve),
      ("ThrottlingValveScriptableComponent hides actions for missing throttling valve",
          ThrottlingValveScriptableComponentTests.HidesActionsForMissingThrottlingValve),
      ("ThrottlingValveScriptableComponent executes open close and set flow actions",
          ThrottlingValveScriptableComponentTests.ExecutesOpenCloseAndSetFlowActions),
      ("ThrottlingValveScriptableComponent builds action definitions for outflow limit",
          ThrottlingValveScriptableComponentTests.BuildsActionDefinitionsForOutflowLimit),
      ("ThrottlingValveScriptableComponent reports unknown action",
          ThrottlingValveScriptableComponentTests.ReportsUnknownAction),
      ("WorkplaceScriptableComponent exposes signal and actions for workplace",
          WorkplaceScriptableComponentTests.ExposesSignalAndActionsForWorkplace),
      ("WorkplaceScriptableComponent hides signal and actions for missing workplace",
          WorkplaceScriptableComponentTests.HidesSignalAndActionsForMissingWorkplace),
      ("WorkplaceScriptableComponent reads assigned workers signal",
          WorkplaceScriptableComponentTests.ReadsAssignedWorkersSignal),
      ("WorkplaceScriptableComponent builds signal and action definitions",
          WorkplaceScriptableComponentTests.BuildsSignalAndActionDefinitions),
      ("WorkplaceScriptableComponent executes worker actions", WorkplaceScriptableComponentTests.ExecutesWorkerActions),
      ("WorkplaceScriptableComponent executes priority action", WorkplaceScriptableComponentTests.ExecutesPriorityAction),
      ("WorkplaceScriptableComponent reports invalid workers priority and action",
          WorkplaceScriptableComponentTests.ReportsInvalidWorkersPriorityAndAction),
      ("WeatherScriptableComponent registers weather extension", WeatherScriptableComponentTests.RegistersWeatherExtension),
      ("WeatherScriptableComponent exposes season signal and definitions",
          WeatherScriptableComponentTests.ExposesSeasonSignalAndDefinitions),
      ("WeatherScriptableComponent initializes and saves current season",
          WeatherScriptableComponentTests.InitializesAndSavesCurrentSeason),
      ("WeatherScriptableComponent uses temperate weather provider and notifies listeners",
          WeatherScriptableComponentTests.UsesTemperateWeatherProviderAndNotifiesListeners),
      ("WeatherScriptableComponent uses hazardous weather when active",
          WeatherScriptableComponentTests.UsesHazardousWeatherWhenActive),
      ("WeatherScriptableComponent reports unknown signal", WeatherScriptableComponentTests.ReportsUnknownSignal),
      ("ReferenceManager tracks action registrations", ReferenceManagerTests.TracksActionRegistrations),
      ("ReferenceManager tracks signal registrations", ReferenceManagerTests.TracksSignalRegistrations),
      ("ReferenceManager notifies host once for matching signal", ReferenceManagerTests.NotifiesHostOnceForMatchingSignal),
      ("ReferenceManager allows registration changes while notifying",
          ReferenceManagerTests.AllowsRegistrationChangesWhileNotifying),
      ("ScriptableComponentBase returns empty definitions by default",
          ScriptableComponentBaseTests.ReturnsEmptyDefinitionsByDefault),
      ("ScriptableComponentBase reports unknown signals and actions",
          ScriptableComponentBaseTests.ReportsUnknownSignalsAndActions),
      ("ScriptableComponentBase load registers scriptable", ScriptableComponentBaseTests.LoadRegistersScriptable),
      ("ScriptableComponentBase formats argument hints", ScriptableComponentBaseTests.FormatsArgumentHints),
      ("ScriptableComponentBase gets component or reports bad state",
          ScriptableComponentBaseTests.GetsComponentOrReportsBadState),
      ("ObjectsCache caches objects by single key", ObjectsCacheTests.CachesObjectsBySingleKey),
      ("ObjectsCache caches objects by composite keys", ObjectsCacheTests.CachesObjectsByCompositeKeys),

      // ScriptingEngineUI
      ("InvertRuleButtonProvider inverts FillValve.SetHeight argument without changing action",
          InvertRuleButtonProviderTests.InvertsFillValveSetHeightArgumentWithoutChangingAction),
      ("InvertRuleButtonProvider inverts FillValve open and close actions",
          InvertRuleButtonProviderTests.InvertsFillValveOpenAndCloseActions),
      ("InvertRuleButtonProvider inverts ThrottlingValve.SetFlow argument without changing action",
          InvertRuleButtonProviderTests.InvertsThrottlingValveSetFlowArgumentWithoutChangingAction),
      ("InvertRuleButtonProvider inverts ThrottlingValve open and close actions",
          InvertRuleButtonProviderTests.InvertsThrottlingValveOpenAndCloseActions),

      // ScriptingEngine.ScriptableComponents.Extensions
      ("AutomationExtensionsRegistry gets registered extension by name and type",
          AutomationExtensionsRegistryTests.GetsRegisteredExtensionByNameAndType),
      ("AutomationExtensionsRegistry ignores duplicate extension registration",
          AutomationExtensionsRegistryTests.IgnoresDuplicateExtensionRegistration),
      ("AutomationExtensionsRegistry returns null for missing extension",
          AutomationExtensionsRegistryTests.ReturnsNullForMissingExtension),
  ];

  static int Main() {
    var failed = 0;
    foreach (var (name, test) in Tests) {
      try {
        test();
        Console.WriteLine("[PASS] " + name);
      } catch (Exception e) {
        failed++;
        Console.WriteLine("[FAIL] " + name);
        Console.WriteLine(e);
      }
    }

    Console.WriteLine();
    Console.WriteLine($"Total: {Tests.Count}, Passed: {Tests.Count - failed}, Failed: {failed}");
    return failed == 0 ? 0 : 1;
  }
}
